version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "build.gradle.kts" }}
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - save_cache:
          key: dependency-cache-{{ checksum "build.gradle.kts" }}
          paths:
            - ~/.gradle
      - run:
          name: Run Checks and Tests
          command: ./gradlew check --stacktrace
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_test_results:
          path: build/test-results/test

  deploy:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "build.gradle.kts" }}
      - run:
          name: Publish Gradle Plugin
          command: ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_SECRET_KEY --stacktrace

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
